### ISSUE TITLE
Frobisher Says does not run when the BMP plugin is active

### ISSUE THREAD

**Issue by anden11** [OperationNT414C/FakeCamera#2]
I'm using an "ALL.bmp" with 64x64 resolution.

When I run the game, it gets stuck on the splash screen right after pressing the bubble.
Normally, it would disappear after circa 10 seconds. Disabling the plugin again allows me to run the game.

**Comment by OperationNT414C** [comment]
Hello,

I checked this game and I confirm your issue. I definitly don't get how this game interacts with the camera API: it calls in a "nearly infinite loop" sceCameraRead and sceCameraIsActive on the application start.
On a classic PS Vita, it continues loading the game after about 1000 calls and I can't figure out what makes "Frobisher Says" application to stop its camera API calls loop.
On PS TV, when I put some traces to see the calls and it seems to break the loop after about 5000 calls.

If you are interested, here is the version with traces which "breaks" the loop (this version also depends on "kuio.skprx", https://github.com/Rinnegatamante/kuio/releases):

[fakecamerabmp.zip](https://github.com/OperationNT414C/FakeCamera/files/1384867/fakecamerabmp.zip)

It is not a good solution because it generates a trace file in "ux0:data" with a size which can highly increase so don't use it with all other games!

**Comment by anden11** [comment]
Ah, thanks for the attention! Anything you need me to test with that alternate version?

**Comment by OperationNT414C** [comment]
Hello,

No, I don't need anything because I already got the game when I bought my PS Vita 5 years ago so I was able to restore my very old CMA backup (PCSF00043) :-).

The good news is that I found a way to fix the startup issue by "releasing" the camera thread (this is what the traces were doing but now, it is with a cleaner way). You can get the clean way here:

[fakecamerabmp.zip](https://github.com/OperationNT414C/FakeCamera/files/1385484/fakecamerabmp.zip)

The bad news is that this game uses the only format I didn't support "SCE_CAMERA_FORMAT_YUV420_PLANE" (because this format implies dependency between picture rows and my current architecture doesn't support it). As it is the first game I met using this format, it will take some time to implement a full solution for this format (the random aspect of mini-game choice won't help!).

**Comment by OperationNT414C** [comment]
Hello,

After some time, I was able to publish a new release which supports "Frobisher Says". There were 3 main issues to support the game:
- For an unknown reason, the game can't normally access to "ux0:/data" (so I had to create a dependency on "kuio.skprx" for kernel file access)
- The game always activates the camera and uses a "camera thread" which continually loops even when the camera isn't used by the current mini-game (by the way, it is a perfect way to drain a real PS Vita battery...): if this behavior is not well managed, it could cause freeze during loading time
- It uses the "SCE_CAMERA_FORMAT_YUV420_PLANE" which I had to implement

Now, I solved all those issues (the solution for the second one is still not perfect because loading times are slowed down by the plugin). You can download the "fakecamerakbmp.suprx" (and the dependencies "dsmotion.skprx" and "kuio.skprx") from version 1.2 to get this game support ;-).

**Comment by anden11** [comment]
Oops, forgot to check back here for quite a while. Thanks a ton for working this out, truly appreciate it!

**Comment by Brayton1234567** [comment]
You should close the issue.

**Comment by OperationNT414C** [comment]
Yes, I forgot to close it because the validation of the issue creator took some time.

About "Welcome Park", in fact, it's already included in PS TV "pd0" partition (like in PS Vita). I managed to add it by editing my "app.db". With the following attachement, you can add everything required to add the possibility of using this application on PS TV (except that the icon and the background will be dirty):
[WelcomePark.zip](https://github.com/OperationNT414C/FakeCamera/files/2254810/WelcomePark.zip)

**Comment by Brayton1234567** [comment]
NPXS10007.sql is encrypted.
