### ISSUE TITLE
ur0 partition

### ISSUE THREAD

**Issue by JohnNathanDrake** [OperationNT414C/FakeCamera#6]
I know the project is abandoned, however I would like to know if I'm doing it wrong, the plugins now work on partition ur0 instead of ux0. The Teareway game started working after I put the fakecamera plugin, but I can't load the image into the game, but I used all possible ways to call the file. Maybe it doesn't work or I have to try to use it on ux0 or is the colleague who opened a poll about ioplus correct?

**Comment by OperationNT414C** [comment]
Hello, long time I did not started my PlayStation TV : I get back the BMP image I used to check this feature.
You can download it (with some additional setup files, like "kuio" because I am not sure it can be found anymore) here:
[TestImageAndKernelSetup.zip](https://github.com/OperationNT414C/FakeCamera/files/7697561/TestImageAndKernelSetup.zip)

Please check this image first, and don't forget that, even if you put FakeCamera in "ur0", the path where the plugin tries to get the image is always "ux0:/data/FakeCamera/".
Please also check with the "fakecamerakbmp.suprx" version of the plugin (by adding "kuio.skprx" in your "config.txt", "*KERNEL" part). With this configuration, you must allow "unsecured homebrews".
Once you validate that you can still, at least see this image, then you can replace it with other BMP images you generate yourself and try to find the "good format".

**Comment by JohnNathanDrake** [comment]
Thank you so much for answering me. Yes, I tried to use it on both ux0 and ur0, but nothing conclusive, I'll see the file you sent me and with your guidance see if I can make it work here on my ps tv, one more question, to call me the image for the game I do I put the line in the config.txt of the tai folder? or in the date folder?

**Comment by JohnNathanDrake** [comment]
Moving on here just to update you, I tried it after you instructed me and unfortunately I can't put the image to appear in the game (I even tried using the pro camera to help me in the test). But I'm glad that at least the game is working. A question, will it be possible one day to connect a webcam to ps tv to simulate as in vita?

**Comment by OperationNT414C** [comment]
> (I even tried using the pro camera to help me in the test)
When I checked my configuration, it was indead with PCM300001 title: unfortunatlely, if you do not manage to make it work on this one, there is no chance that it will work in more complex titles.
With BMP versions of FakeCamera, there is a mandatory dependency on "dsmotion.skprx" plugin: did you put it too?
> will it be possible one day to connect a webcam to ps tv to simulate as in vita?
It would require to develop webcam drivers (including the fact that some cameras have not a generic protocol). It would be a very long and complex project and unfortunately, I do not have the time to do it.

**Comment by JohnNathanDrake** [comment]
I put the plugin yes (dsmotion), but about the part I asked you about calling the image in the game, where do I put the command line? in tai (config.txt) or elsewhere.

**Comment by OperationNT414C** [comment]
Can you share your "config.txt" file?

There is no "in game command" in order to activate an image with the plugin, only a logic in the plugin to look at successive paths described in the readme:
"ux0:data/FakeCamera/TITLEID00_Front.bmp" or "ux0:data/FakeCamera/TITLEID00_Back.bmp" (depends on front or back camera use)
"ux0:data/FakeCamera/TITLEID00.bmp"
"ux0:data/FakeCamera/ALL_Front.bmp" or "ux0:data/FakeCamera/ALL_Back.bmp" (depends on front or back camera use)
"ux0:data/FakeCamera/ALL.bmp"
